name: Greenspeed
favicon: null
layout_spectrum: 0.7834503357298672
typography_spectrum: 0.1454271236434579
title: Elsykkelspesialisten
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.409761365968734
  lightness: 0.5762820288073272
  saturation: 0.45469291508197784
  rhythmicContrast: 0.5538389014545828
purpose: []
